baseurl = "https://muplant.gitee.io/"
title = "Black & Light"
author = "Choy"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "穆 道"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "#"
[[menu.main]]
    name = "Projects"
    url  = "#"
[[menu.main]]
    name = "Resume"
    url  = "#"