baseurl = "localhost"
languageCode = "en-us"
paginate = 10
theme = "hello-friend-ng"
title = "My Blog"

[params]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
dateformShort = "Jan 2"

# Subtitle for home
homeSubtitle = "A simple and beautiful blog"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
images = [""]
keywords = "homepage, blog"

[taxonomies]
category = "blog"
series = "series"
tag = "tags"

[languages]
[languages.en]
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
keywords = ""
readOtherPosts = "Read other posts"
subtitle = "A simple theme for Hugo"
title = "Hello Friend NG"

[languages.en.params.logo]
logoHomeLink = "/"
logoText = "hello friend ng"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
